name: Build GR33N PS3 PKG

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make curl python3 texinfo bison flex

      - name: Download PSL1GHT Precompiled Toolchain
        run: |
          curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xvz -C ./
          echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
          echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/ps3dev/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/ps3dev/ppu/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/ps3dev/spu/bin" >> $GITHUB_PATH

      - name: Install pthread-emb library
        run: |
          curl -sL https://github.com/bucanero/pthread-emb-ps3/tarball/master | tar xvz -C ./
          cd bucanero-pthread-emb-ps3-*/platform/psl1ght
          make install
          mkdir -p ${GITHUB_WORKSPACE}/ps3dev/ppu/include ${GITHUB_WORKSPACE}/ps3dev/ppu/lib
          cp -R ../../include/* ${GITHUB_WORKSPACE}/ps3dev/ppu/include/ || true
          cp libpthread.a ${GITHUB_WORKSPACE}/ps3dev/ppu/lib/ || true

      - name: Build dependencies
        run: |
          chmod +x deps/*.sh
          cd deps
          ./build-mbedtls.sh
          ./build-libsrtp.sh
          ./build-usrsctp.sh
          ./build-libpeer.sh
          ./build-opus.sh
          cd ..

      - name: Compile PKG
        run: |
          make pkg

      - name: Upload PKG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gr33n-wifi-fix-pkg
          path: |
            gr33n.pkg
            gr33n.self
